"usse client"
import React from 'react'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const HomePage = () => {

  return (
    <div className='h-max w-full'>

    </div>
  )
}

export default HomePage